#
# MIT License
#
# (C) Copyright [2022] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spire.fullname" . }}-update-bss-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ template "spire.name" . }}-update-bss
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "spire.name" . }}-update-bss
    spec:
      serviceAccountName: {{ include "spire.fullname" . }}-update-bss
      containers:
        - name: update-bss
          image: "{{ .Values.bss.curl.repository }}:{{ .Values.bss.curl.tag }}"
          command:
            - '/bin/sh'
            - '-x'
            - '-c'
          args:
            - 'retries=1;
               while ! curl -fv --request PATCH -H "Content-Type: application/json" -d @/conf/bss-update.json "$ENDPOINT";
                 do if [ $retries -gt 9 ];
                   then echo "Failed to add spire entry to BSS";
                   exit 1;
                 fi;
                 echo "Failed to patch BSS. Retrying ($retries/10)";
                 retries=$(expr $retries + 1);
                 sleep 30;
               done'
          env:
            - name: ENDPOINT
              value: "{{ .Values.bss.endpoint }}"
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: conf
          configMap:
            name: {{ include "spire.fullname" . }}-bss-config
